import React from "react";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { Metadata } from "next/types";
import Client from "./client";

export const metadata: Metadata = {
  title: "Budgeting Dashboard",
  description: "Generated by create next app",
  icons: "/wallet.png",
};

export default function ({ children }: { children: React.ReactNode }) {
  return (
    <main>
      <Theme>
        <Client>{children}</Client>
      </Theme>
    </main>
  );
}
